# backend/fly.toml
app = "posterscoop-api"
primary_region = "ams"

[build]
dockerfile = "Dockerfile"

[env]
PORT = "8080"
PYTHONUNBUFFERED = "1"
FLASK_APP = "app.py"          # <-- so release_command can find your app

[deploy]
  release_command = "python -m flask db upgrade"   # <-- runs once each deploy, before machines start

[[services]]
internal_port = 8080
protocol = "tcp"

  [[services.ports]]
  port = 80
  handlers = ["http"]

  [[services.ports]]
  port = 443
  handlers = ["tls", "http"]

  [[services.tcp_checks]]
  interval = "15s"
  timeout = "2s"
  grace_period = "30s"
  restart_limit = 0

[[vm]]
size = "shared-cpu-1x"
memory = "512mb"
