export const MAIN_CATEGORIES = [
  'Movies',
  'TV Series',
  'Anime',
  'Games',
  'Music',
  'Quotes',
  'Art & Aesthetic',
  'Sports',
  'Bangladeshi Culture',
  'Nature & Landscapes',
  'Motivational',
  'Minimalist',
  'Typography',
  'Sci-Fi & Fantasy',
  'Comics',
  'Cartoons',
  'Abstract',
  'Space & Galaxy',
  'City & Architecture',
  'Vintage / Retro',
];
